### ISSUE TITLE
Caching docs are missing information on timeunits

### ISSUE THREAD

**Issue by tarjei** [doctrine/common-documentation#11]
Hi, I read through this document: http://docs.doctrine-project.org/en/latest/reference/caching.html looking for information on what timeunits the expiration time of save() uses, but I didn't find any information on it.

I then tried to find out where I should create a PR, but I also failed at that so now I'm reduced to writing a bugreport :)

Anyhow, IMHO the documentation should be more spesific on which timeunit you are specifying for the lifeTime parameter to save().

Regards,
Tarjei

**Comment by mikeSimonson** [comment]
@tarjei That documentation is in the doctrine2 repo.
https://github.com/doctrine/doctrine2/blob/master/docs/en/reference/caching.rst
